#!/usr/bin/env bash
# One-line install for qubox-host-agent (+ client-cli) on Linux/macOS.
#
# From a clone:
#   ./scripts/install-host-agent.sh
#
# Env:
#   QUBOX_PREFIX      install prefix (default: $HOME/.local)
#   QUBOX_SERVER      written into ~/.config/qubox/env (optional)
#   QUBOX_SKIP_BUILD  if set and no local binary, fail instead of building
set -euo pipefail

log() { printf '+ %s\n' "$*"; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PREFIX="${QUBOX_PREFIX:-$HOME/.local}"
BIN_DIR="$PREFIX/bin"
CFG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/qubox"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
mkdir -p "$BIN_DIR" "$CFG_DIR"

install_bins_from() {
  local src="$1"
  [[ -x "$src/qubox-host-agent" ]] || return 1
  install -m 755 "$src/qubox-host-agent" "$BIN_DIR/qubox-host-agent"
  if [[ -x "$src/qubox-client-cli" ]]; then
    install -m 755 "$src/qubox-client-cli" "$BIN_DIR/qubox-client-cli"
  fi
  return 0
}

if install_bins_from "$REPO_ROOT/target/release"; then
  log "Installed from local release build → $BIN_DIR"
elif install_bins_from "$REPO_ROOT/dist/linux-$(uname -m)"; then
  log "Installed from dist/ → $BIN_DIR"
elif [[ -n "${QUBOX_SKIP_BUILD:-}" ]]; then
  die "no prebuilt binary and QUBOX_SKIP_BUILD is set"
else
  command -v cargo >/dev/null 2>&1 || die "cargo not found; install Rust from https://rustup.rs"
  log "Building release host-agent + client-cli (several minutes)..."
  (cd "$REPO_ROOT" && cargo build --release -p qubox-host-agent -p qubox-client-cli)
  install_bins_from "$REPO_ROOT/target/release" || die "build finished but binaries missing"
  log "Installed → $BIN_DIR/{qubox-host-agent,qubox-client-cli}"
fi

if [[ -n "${QUBOX_SERVER:-}" ]]; then
  cat >"$CFG_DIR/env" <<EOF
# Generated by install-host-agent.sh
export QUBOX_SERVER=${QUBOX_SERVER}
EOF
  log "Wrote $CFG_DIR/env"
fi

if [[ "$(uname -s)" == "Linux" ]] && command -v systemctl >/dev/null 2>&1; then
  mkdir -p "$UNIT_DIR"
  cat >"$UNIT_DIR/qubox-host-agent.service" <<'EOF'
[Unit]
Description=Qubox host agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=-%h/.config/qubox/env
ExecStart=%h/.local/bin/qubox-host-agent --name %H
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
EOF
  log "Wrote $UNIT_DIR/qubox-host-agent.service"
  log "Enable with: systemctl --user daemon-reload && systemctl --user enable --now qubox-host-agent"
fi

case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *) log "Add to PATH: export PATH=\"$BIN_DIR:\$PATH\"" ;;
esac

cat <<'EOF'

Next:
  export QUBOX_SERVER=${QUBOX_SERVER:-ws://127.0.0.1:7000/ws}
  qubox-host-agent --server "$QUBOX_SERVER" --name "$(hostname)"

Self-host stack:
  docker compose -f ops/self-host/docker-compose.yml up -d --build

Security:
  Never use --auto-approve-pairing on internet-facing hosts.
  Auto-approve is refused for non-local signaling URLs.
EOF
